apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiharnesses.bob.inklogic.tech
spec:
  group: bob.inklogic.tech
  names:
    kind: AiHarness
    listKind: AiHarnessList
    plural: aiharnesses
    singular: aiharness
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              type:
                type: string
              secretRef:
                type: string
            type: object
        type: object
    served: true
    storage: true