apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.postgres.lab.inklogic.tech
spec:
  group: postgres.lab.inklogic.tech
  names:
    kind: Restore
    listKind: RestoreList
    plural: restores
    singular: restore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              phase:
                enum:
                - Pending
                - Running
                - Succeeded
                - Failed
                type: string
              completedAt:
                format: date-time
                nullable: true
                type: string
              selfDeleteAt:
                format: date-time
                nullable: true
                type: string
              message:
                nullable: true
                type: string
            type: object
          spec:
            properties:
              backupName:
                type: string
              clearData:
                type: boolean
              databaseName:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}