apiVersion: v2
name: bob-crds
description: 'Custom Resource Definitions (CRDs) for the Bob operator. Contains all
  CRDs for the bob.inklogic.tech API group. This chart must be installed before bob-operator
  on every cluster.

  '
type: application
version: 2026.5.32
appVersion: "2a4e03e"
keywords:
- bob
- operator
- crds
- inklogic
home: https://github.com/ink-logic/bob
sources:
- https://github.com/ink-logic/bob
maintainers:
- name: ink-logic
  url: https://github.com/ink-logic
annotations:
  artifacthub.io/category: integration-delivery
  bob.inklogic.tech/source-commit: 2a4e03e3c4c7082476036b2b95e777d10278e218
  bob.inklogic.tech/source-commit-short: 2a4e03e
