apiVersion: v2
name: bob-crds
description: 'Custom Resource Definitions (CRDs) for the Bob operator. Contains all
  CRDs for the bob.inklogic.tech API group. This chart must be installed before bob-operator
  on every cluster.

  '
type: application
version: 2026.5.53
appVersion: "860d968"
keywords:
- bob
- operator
- crds
- inklogic
home: https://github.com/ink-logic/bob
sources:
- https://github.com/ink-logic/bob
maintainers:
- name: ink-logic
  url: https://github.com/ink-logic
annotations:
  artifacthub.io/category: integration-delivery
  bob.inklogic.tech/source-commit: 860d9689926c4c033c2357af3f07982b2ef076e6
  bob.inklogic.tech/source-commit-short: 860d968
