apiVersion: v2
name: bob-crds
description: 'Custom Resource Definitions (CRDs) for the Bob operator. Contains all
  CRDs for the bob.inklogic.tech API group. This chart must be installed before bob-operator
  on every cluster.

  '
type: application
version: 2026.5.57
appVersion: "f4d1134"
keywords:
- bob
- operator
- crds
- inklogic
home: https://github.com/ink-logic/bob
sources:
- https://github.com/ink-logic/bob
maintainers:
- name: ink-logic
  url: https://github.com/ink-logic
annotations:
  artifacthub.io/category: integration-delivery
  bob.inklogic.tech/source-commit: f4d11340729a974f947770d3bac06f47f93c126f
  bob.inklogic.tech/source-commit-short: f4d1134
